### PR TITLE
added an improved version of stemming algorithm

### PR DESCRIPTION
**Pull request by imVivekGupta**
#3 splitting by the 2nd word of the corpora list doesn't appear to be very effective. Consider this:
`'अंगूठे\tअंगूठा'`
Going by the implemented algorithm, we get 'अंगूठे' as the inflection. 
Instead, I propose, finding the common prefix and using the uncommon suffix part as the inflection. I have implemented this idea.

### CODE REVIEW

**Comment by djokester** [comment]
The indentation is all wrong! Please do correct it. This is a good commit otherwise!

**Comment by imVivekGupta** [comment]
Corrected! :)

**Comment by djokester** [comment]
Errr... It's still wrong. Check return words indentation

**Comment by imVivekGupta** [comment]
Please check now.

**Comment by djokester** [comment]
Return words should be just one indent away from the function declaration. Are you testing the file before sending the PR?

**Comment by imVivekGupta** [comment]
"words" would be defined only when control enters the if block, wouldn't it? It should be 2 indents away from function declaration this way. Yes, I have tested this file. It works.

**Comment by djokester** [comment]
Define words outside the if block.
Add an error case in an else statement.

**Comment by imVivekGupta** [comment]
Added error case for wrong input. Please review.

**Comment by djokester** [comment]
Hey @imVivekGupta 
I am sorry I was busy for a few days! I think we can work with this. 
Give me a few hours to review this! Thank You!

**Pull request closed without merging**
